server:
  port: 80
spring:
  application:
    name: atguigu-crowd-zuul
  redis:
    host: 192.168.240.128
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*" #忽略原本微服务名称
  sensitive-headers: "*"  # 在Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:               #自定义路由规则
    crowd-portal:       #自定义路由规则名称
      service-id: atguigu-crowd-auth  #针对portal-view微服务设置路由规则
      path: /**  # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000